apiVersion: apps/v1
kind: Deployment
metadata:
  name: realsmile-backend
  namespace: {{ .Values.namespace }}
  labels: 
    app: realsmile-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels: 
      app: realsmile-backend
  template: 
    metadata:
      labels:
        app: realsmile-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: realsmile-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

