replicaCount: 2

image:
  repository: realsmile-backend
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

namespace: realsmile
