apiVersion: v1
kind: Service
metadata:
  name: rollback-controller
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: rollback-controller
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP